name: Cron

on:
  schedule:
    - cron: "0,30 12 1,15 * *"
  push:
    branches:
      - "main"

jobs:
  # delegation-gravity1c4t4aqe74yyz624dm44u6xhfz9p8rx4f90jxjl:
  delegation-community:
    runs-on: ubuntu-20.04
    environment: delegation_env
    steps:
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v1.5.0
        with:
          status: ${{ job.status }}
          channel: "#cosmos-hub-github-actions"
          steps: ${{ toJson(steps) }}
          message: Starting Gravity Delegation bot for community wallet
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: 🍽️ Checkout the repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install dependencies
        id: dependencies
        run: |
          # setting delay so as to allow multisig delegation to run
          sleep 30

          # update basic
          # install dependencies
          sudo apt-get update &&  sudo apt-get install wget bash jq python3 -y && \
          # download gravity bin
          wget https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.4.0/gravity-linux-amd64 && \
          # configure gravity
          mv gravity-linux-amd64 gravity && \
          chmod +x gravity && \
          sudo mv gravity /usr/bin/
      - name: setup authz account
        id: setup
        env:
          AUTHZ_PHRASES: ${{ secrets.AUTHZ_PHRASES }}
        run: |
          echo "$AUTHZ_PHRASES" | gravity keys add gravity-bot --keyring-backend test --recover
      - name: Run Automation
        id: exec
        run: ./delegate.sh
        env:
          DENOM: ${{ secrets.DENOM }}
          BINARY: ${{ secrets.BINARY }}
          GRANTEE: ${{ secrets.GRANTEE }}
          FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          MAX_AMOUNT: ${{ secrets.MAX_AMOUNT }}
          NODE: ${{ secrets.NODE }}
          AUTHZ_PHRASES: ${{ secrets.AUTHZ_PHRASES }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
        env:
          SLACK_WEBHOOK_URL:
            ${{ secrets.SLACK_WEBHOOK_URL }}

            # delegation-gravity1zk4uwzygs4k2k5cz7y759sxcnv6qt3pd4g3pqq:
  delegation-multisig:
    runs-on: ubuntu-20.04
    environment: delegation-gravity1zk4uwzygs4k2k5cz7y759sxcnv6qt3pd4g3pqq
    steps:
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v1.5.0
        with:
          status: ${{ job.status }}
          channel: "#cosmos-hub-github-actions"
          steps: ${{ toJson(steps) }}
          message: Starting Gravity Delegation bot for multisig wallet
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: 🍽️ Checkout the repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install dependencies
        id: dependencies
        run: |
          # update basic
          # install dependencies
          sudo apt-get update &&  sudo apt-get install wget bash jq python3 -y && \
          # download gravity bin
          wget https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.4.0/gravity-linux-amd64 && \
          # configure gravity
          mv gravity-linux-amd64 gravity && \
          chmod +x gravity && \
          sudo mv gravity /usr/bin/
      - name: setup authz account
        id: setup
        env:
          AUTHZ_PHRASES: ${{ secrets.AUTHZ_PHRASES }}
        run: |
          echo "$AUTHZ_PHRASES" | gravity keys add gravity-bot --keyring-backend test --recover
      - name: Run Automation
        id: exec
        run: ./delegate.sh
        env:
          DENOM: ${{ secrets.DENOM }}
          BINARY: ${{ secrets.BINARY }}
          GRANTEE: ${{ secrets.GRANTEE }}
          FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          MAX_AMOUNT: ${{ secrets.MAX_AMOUNT }}
          NODE: ${{ secrets.NODE }}
          AUTHZ_PHRASES: ${{ secrets.AUTHZ_PHRASES }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
